config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :books, only: [:show, :index] do
    member do 
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do 
        post 'vote'
      end
    end
  end

  get '/register', to: 'users#new'
  resources :users, except: [:new, :index]

  resources :categories, only: [:show]

end

app/models/book.rb
class Book < ActiveRecord::Base
  include Voteable
  
  belongs_to :user

  has_many :books_categories
  has_many :categories, through: :books_categories
  has_many :comments
end

app/models/books_category.rb
class BooksCategory < ActiveRecord::Base
  belongs_to :book
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books_categories
  has_many :books, through: :books_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # make available in views
  helper_method :current_user, :logged_in?

  def current_user
    # the ||= is a memorization. Says if it exists don't run the code. 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash["error"] = "Must be logged in."
      redirect_to login_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def vote
    @book = Book.find(params[:id])
    @vote = Vote.create(voteable: @book, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flass[:notice] = "Your vote was counted."
        else
          flass[:error] = "You've voted on this book in this category already."
        end
        redirect_to :back
      end
      format.js
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.where(username: params[:username]).first
  
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, " + user.username + "! You've logged in."
      redirect_to root_path
    else
      flash[:error] = "Login information is incorrect."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome, " + @user.username + "! You're signed up."
      # auto log user and set to defualt user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "I'm sorry that username is already taken."
      render :new
    end
  end

  private

  def user_params
    # sanitize/validate with strong parameters
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def determine_active(cat)
    active?(cat) ? "active" : ""
  end

  def active?(cat)
    cat == @category
  end
end

app/views/books/_book.html.erb
<li class="media-object well">
  <div class="book">
    <h3>
      <%= link_to book.title, book_path(book) %> 
    </h3>
    <div class="quiet">by <%= book.author %></div>
    <hr>
    <div class="text-center">
      <img class="small-cover" src="<%= book.cover_url %>">
    </div>
  </div>
  <br>
  <div>
    <%= link_to vote_book_path(book, vote: false), method: 'post', remote: true do %>
      <i class="subtract-vote glyphicon glyphicon-minus"></i>
    <% end %>
    <div id="book_<%= book.id %>_votes" class="votes"><span><%= book.diff_votes %> votes</span></div>
   
    <%= link_to vote_book_path(book, vote: true), method: 'post', remote: true do %>
      <i class="add-vote glyphicon glyphicon-plus"></i>
    <% end %>
  </div>
</li>

app/views/books/index.html.erb
<%= render 'shared/content_title.html.erb', title: "All Books" %>

<%= render 'layouts/categories' %>

<div class="container">
  <ul class="list-inline text-center">
    <% @books.each do |book| %>
      <%= render 'book', book: book %>
    <% end %>
  </ul>
</div

app/views/books/show.html.erb
<%= render 'shared/content_title.html.erb', title: @book.title %>

<div class="text-center">
  <h3>Author: <%= @book.author %></h3>
</div>

<br>

<div class="row">
  <div class="text-center col-xs-7">
    <img src="<%= @book.cover_url %>">
  </div>
  <div class="col-xs-4">
    <dl>
      <dt>Why Read It</dt>
      <dd><%= @book.why %></dd>
      <dt>Endorsed By</dt>
      <dd>ADD ENDORSEMENT COLUMN</dd>
      <dt>Description</dt>
      <dd><%= @book.what %></dd>
      <dt>Book Type</dt>
      <dd><%= @book.how %></dd>
      <dt>Tags</dt>
      <dd>ADD TAGS COLUMN</dd>
    </dl>    
  </div>
</div>

app/views/books/vote.js.erb
<% if @vote.valid? %>
  $('#book_<%= @book.id %>_votes').html("<%= @book.diff_votes %> votes")
<% else %>
  alert("You can vote on a book once per category.")
<% end %>

app/views/categories/show.html.erb
<%= render 'shared/content_title.html.erb', title: @category.tag.capitalize %>

<%= render 'layouts/categories' %>

<div class="container">
  <ul class="list-inline text-center">
    <% @category.books.each do |book| %>
      <%= render 'books/book', book: book %>
    <% end %>
  </ul>
</div

app/views/layouts/_categories.html.erb
<div class="tabs-left">
  <ul class="nav nav-tabs">
    <li class="<%= determine_active(nil) %>">
      <%= link_to(books_path) do %>
        <span class="glyphicon glyphicon-cloud"></span>
      <% end %>
    </li>
    <% @categories.each do |category| %>
    <li class="<%= determine_active(category) %>">
      <%= link_to(category_path(category)) do %>
        <span class="glyphicon glyphicon-<%= category.glyphicon %>"></span>
      <% end %>
    </li>
    <% end %>
  </ul>
</div><!-- /tabbable -->



<!-- 
All                       -> cloud
Biographies & Inspiration -> user
Nueroscience & Psychology -> wrench
Health & Physiology       -> tint
Biology                   -> tree-deciduous
Living Rightly            -> map-marker
Computer Science          -> phone
 -->

    

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= image_tag("logo", class: "logo") %>
      </a>
      <%= link_to "Top Books", root_path, :class => "navbar-brand" %>
    <% if logged_in? %>
      <div class='nav_item pull-right'>
        <%= link_to logout_path do %>
          <i class="glyphicon glyphicon-circle-arrow-left"></i>
          Logout
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<div id="main" role="main">
  <div class="container">
     <div class="row">
      <div class="span12">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
    <footer>
    </footer>
  </div> <!--! end of .container -->
</div>

</body>
</html>

app/views/shared/_content_title.html.erb
<div class="page-header text-center">
  <h1><%= title %></h1>
</div>

app/views/users/new.html.erb
<%= render "shared/content_title", title: "Register" %>

<div class="well text-center">
<%= form_for @user do |f| %>
  <div class='control-group'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class='control-group'>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <%= f.submit (@user.new_record? ? "Register" : "Update"), class: "btn btn-success" %>
<% end %>
</div>